"use client";

import { useSignalStore } from "@/store/useSignalStore";
import { Sparkles } from "lucide-react";

export function AIAnalysisCard() {
  const { activeSignals } = useSignalStore();
  const activeSignal = activeSignals[0];

  if (!activeSignal || !activeSignal.aiAnalysis) {
    return (
      <div className="space-y-4">
        <p className="text-muted-foreground text-sm">No active signal analysis generated by AI yet.</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="p-4 rounded-xl bg-primary/10 border border-primary/20 relative">
        <Sparkles className="absolute top-4 right-4 w-5 h-5 text-primary opacity-50" />
        <p className="text-sm leading-relaxed text-card-foreground pr-8">
          {activeSignal.aiAnalysis}
        </p>
      </div>
    </div>
  );
}
